In [2]:
import pandas as pd

df = pd.read_csv("supply_chain_extended_data (2).csv")

In [ ]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Warehouse_ID           500 non-null    object
 1   Location               500 non-null    object
 2   Current_Stock          500 non-null    int64
 3   Demand_Forecast        500 non-null    int64
 4   Lead_Time_Days         500 non-null    int64
 5   Shipping_Time_Days     500 non-null    int64
 6   Stockout_Risk          500 non-null    int64
 7   Operational_Cost       500 non-null    int64
 8   Supplier_ID            500 non-null    object
 9   Product_Category       500 non-null    object
 10  Monthly_Sales          500 non-null    int64
 11  Order_Processing_Time  500 non-null    float64
 12  Return_Rate            500 non-null    float64
 13  Customer_Rating        500 non-null    float64
 14  Warehouse_Capacity     500 non-null    int64
 15  Storage_Cost           500 non-null    int64
 16  Transportation_Cost    500 non-null    int64
 17  Backorder_Quantity     500 non-null    int64
 18  Damaged_Goods          500 non-null    int64
 19  Employee_Count         500 non-null    int64
dtypes: float64(3), int64(13), object(4)
memory usage: 78.3+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

Warehouse_ID              object
Location                  object
Current_Stock              int64
Demand_Forecast            int64
Lead_Time_Days             int64
Shipping_Time_Days         int64
Stockout_Risk              int64
Operational_Cost           int64
Supplier_ID               object
Product_Category          object
Monthly_Sales              int64
Order_Processing_Time    float64
Return_Rate              float64
Customer_Rating          float64
Warehouse_Capacity         int64
Storage_Cost               int64
Transportation_Cost        int64
Backorder_Quantity         int64
Damaged_Goods              int64
Employee_Count             int64
dtype: object

In [ ]:
df.select_dtypes(include='object').head()

  Warehouse_ID Location Supplier_ID Product_Category
0        WH239   Dallas        S693        Groceries
1        WH244  Houston        S880      Electronics
2        WH340  Chicago        S116        Furniture
3        WH428  Atlanta        S431          Apparel
4        WH202   Dallas        S821      Electronics

In [ ]:
df.isnull().sum()

Warehouse_ID             0
Location                 0
Current_Stock            0
Demand_Forecast          0
Lead_Time_Days           0
Shipping_Time_Days       0
Stockout_Risk            0
Operational_Cost         0
Supplier_ID              0
Product_Category         0
Monthly_Sales            0
Order_Processing_Time    0
Return_Rate              0
Customer_Rating          0
Warehouse_Capacity       0
Storage_Cost             0
Transportation_Cost      0
Backorder_Quantity       0
Damaged_Goods            0
Employee_Count           0
dtype: int64

In [ ]:
(df.select_dtypes(include='number') < 0).sum()

Current_Stock            0
Demand_Forecast          0
Lead_Time_Days           0
Shipping_Time_Days       0
Stockout_Risk            0
Operational_Cost         0
Monthly_Sales            0
Order_Processing_Time    0
Return_Rate              0
Customer_Rating          0
Warehouse_Capacity       0
Storage_Cost             0
Transportation_Cost      0
Backorder_Quantity       0
Damaged_Goods            0
Employee_Count           0
dtype: int64

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df['Shipping_Time_Days'].describe()

count    500.000000
mean       3.948000
std        1.921635
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max        7.000000
Name: Shipping_Time_Days, dtype: float64

In [ ]:
df.groupby('Warehouse_ID')['Shipping_Time_Days'].mean().sort_values(ascending=False)

Warehouse_ID
WH008    7.0
WH042    7.0
WH470    7.0
WH472    7.0
WH083    7.0
        ...
WH402    1.0
WH143    1.0
WH118    1.0
WH072    1.0
WH459    1.0
Name: Shipping_Time_Days, Length: 313, dtype: float64

In [ ]:
warehouse_mean = df.groupby('Warehouse_ID')['Shipping_Time_Days'].mean()
warehouse_mean[warehouse_mean > 4]

Warehouse_ID
WH005    4.5
WH008    7.0
WH009    4.5
WH010    6.0
WH013    7.0
        ...
WH487    6.0
WH490    4.5
WH491    4.5
WH493    4.5
WH496    6.0
Name: Shipping_Time_Days, Length: 128, dtype: float64

In [ ]:
df.groupby('Location')['Shipping_Time_Days'].mean().sort_values(ascending=False)

Location
Denver           4.391304
New York         4.370370
Miami            4.107143
Chicago          4.068182
San Francisco    4.038462
Atlanta          3.963636
Dallas           3.901961
Houston          3.886364
Seattle          3.454545
Los Angeles      3.277778
Name: Shipping_Time_Days, dtype: float64

In [ ]:
df['Order_Processing_Time'].describe()

count    500.000000
mean       2.750462
std        1.262967
min        0.505159
25%        1.644623
50%        2.817771
75%        3.782273
max        4.954139
Name: Order_Processing_Time, dtype: float64

In [ ]:
df['Processing_Speed'] = pd.cut(
    df['Order_Processing_Time'],
    bins=[0, 2, 4, 10],
    labels=['Fast', 'Average', 'Slow']
)

In [ ]:
df.groupby('Processing_Speed')['Shipping_Time_Days'].mean()

/tmp/ipython-input-244490771.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Processing_Speed')['Shipping_Time_Days'].mean()

Processing_Speed
Fast       3.844720
Average    3.995781
Slow       4.000000
Name: Shipping_Time_Days, dtype: float64

In [ ]:
df['Employee_Count'].describe()

count    500.000000
mean      52.810000
std       27.888087
min        5.000000
25%       28.000000
50%       53.000000
75%       78.000000
max      100.000000
Name: Employee_Count, dtype: float64

In [ ]:
df['Staff_Level'] = pd.cut(
    df['Employee_Count'],
    bins=[0, 20, 50, 100],
    labels=['Low', 'Medium', 'High']
)

In [ ]:
df.groupby('Staff_Level')['Shipping_Time_Days'].mean()

/tmp/ipython-input-3371911626.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Staff_Level')['Shipping_Time_Days'].mean()

Staff_Level
Low       3.915663
Medium    3.922078
High      3.973384
Name: Shipping_Time_Days, dtype: float64

In [ ]:
df['Lead_Time_Days'].describe()

count    500.000000
mean       5.958000
std        2.630223
min        2.000000
25%        4.000000
50%        6.000000
75%        8.000000
max       10.000000
Name: Lead_Time_Days, dtype: float64

In [ ]:
df['Lead_Time_Category'] = pd.cut(
    df['Lead_Time_Days'],
    bins=[0, 3, 6, 10],
    labels=['Low', 'Medium', 'High']
)

In [ ]:
df.groupby('Lead_Time_Category')['Shipping_Time_Days'].mean()

/tmp/ipython-input-2457676684.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Lead_Time_Category')['Shipping_Time_Days'].mean()

Lead_Time_Category
Low       3.964286
Medium    3.910180
High      3.968326
Name: Shipping_Time_Days, dtype: float64

In [ ]:
warehouse_metrics = (df.groupby('Warehouse_ID').agg({'Shipping_Time_Days': 'mean','Order_Processing_Time': 'mean','Employee_Count': 'mean'}))

In [ ]:
warehouse_metrics['Time_Difference'] = (warehouse_metrics['Order_Processing_Time'] - warehouse_metrics['Shipping_Time_Days'])

In [ ]:
final_warehouses = warehouse_metrics[(warehouse_metrics['Shipping_Time_Days'] < warehouse_metrics['Order_Processing_Time'])
 & (warehouse_metrics['Time_Difference'] > 2)]

In [ ]:
final_warehouses.sort_values('Time_Difference', ascending=False)

,Shipping_Time_Days,Order_Processing_Time,Employee_Count,Time_Difference
Warehouse_ID,,,,
WH143,1.0,4.650513,33.0,3.650513
WH151,1.0,4.511183,32.0,3.511183
WH220,1.0,4.272494,48.0,3.272494
WH251,1.0,4.231504,84.0,3.231504
WH349,1.5,4.436630,33.0,2.936630
WH381,2.0,4.935029,15.0,2.935029
WH402,1.0,3.882602,64.0,2.882602
WH250,1.0,3.635330,36.0,2.635330
WH391,2.0,4.562037,51.0,2.562037
WH395,1.0,3.552012,48.0,2.552012
WH223,2.0,4.452742,70.0,2.452742
WH192,1.5,3.883240,41.5,2.383240
WH239,2.0,4.301937,55.5,2.301937
WH459,1.0,3.265891,55.0,2.265891
WH224,1.0,3.225959,15.0,2.225959
WH499,1.5,3.654340,60.0,2.154340
WH380,2.0,4.152379,12.0,2.152379
WH331,2.0,4.147033,86.0,2.147033
WH263,1.5,3.638426,25.5,2.138426
WH396,2.0,4.108624,79.0,2.108624
WH072,1.0,3.090093,66.0,2.090093

## **OBJECTIVE2**

In [ ]:
df[['Current_Stock', 'Demand_Forecast', 'Backorder_Quantity']].describe()

       Current_Stock  Demand_Forecast  Backorder_Quantity
count     500.000000       500.000000          500.000000
mean     2722.822000      2957.050000          147.380000
std      1314.878786      1398.763988           87.880656
min       519.000000       402.000000            0.000000
25%      1565.250000      1745.750000           71.750000
50%      2670.000000      3094.000000          141.000000
75%      3842.750000      4152.500000          224.000000
max      4998.000000      5200.000000          300.000000

In [ ]:
(df['Current_Stock'] - df['Demand_Forecast']).describe()

count     500.000000
mean     -234.228000
std      2003.662878
min     -4575.000000
25%     -1747.250000
50%      -209.000000
75%      1188.500000
max      4275.000000
dtype: float64

In [ ]:
warehouse_inventory = (
    df.groupby('Warehouse_ID')
    .agg({
        'Current_Stock': 'mean',
        'Demand_Forecast': 'mean',
        'Backorder_Quantity': 'mean'
    })
)

In [ ]:
warehouse_inventory

              Current_Stock  Demand_Forecast  Backorder_Quantity
Warehouse_ID
WH001                3764.0           3637.5                31.5
WH002                4387.0           2175.0               137.0
WH005                2669.5           3482.0               101.0
WH006                1314.0           4858.0                70.0
WH007                3308.0           2988.5                31.0
...                     ...              ...                 ...
WH494                3139.0           1614.0                76.0
WH495                3416.0           1803.5               122.0
WH496                4862.0           4621.0               264.0
WH499                3740.5           3330.5               167.5
WH500                4798.0           2861.0               136.0

[313 rows x 3 columns]

In [ ]:
understocked = warehouse_inventory[
    warehouse_inventory['Current_Stock'] <
    warehouse_inventory['Demand_Forecast']
]
understocked

              Current_Stock  Demand_Forecast  Backorder_Quantity
Warehouse_ID
WH005                2669.5      3482.000000          101.000000
WH006                1314.0      4858.000000           70.000000
WH008                4757.0      4776.000000          237.000000
WH010                 853.0      4822.000000          241.000000
WH020                2734.0      4605.000000          195.000000
...                     ...              ...                 ...
WH486                1630.0      4588.000000          228.000000
WH488                2190.0      2705.666667          232.666667
WH490                2358.5      4270.000000          176.500000
WH491                2537.0      3202.500000          154.000000
WH493                4190.5      4305.000000          182.000000

[176 rows x 3 columns]

In [ ]:
overstocked = warehouse_inventory[
    warehouse_inventory['Current_Stock'] >
    warehouse_inventory['Demand_Forecast']
]
overstocked

              Current_Stock  Demand_Forecast  Backorder_Quantity
Warehouse_ID
WH001                3764.0           3637.5                31.5
WH002                4387.0           2175.0               137.0
WH007                3308.0           2988.5                31.0
WH009                3845.0            831.5               129.0
WH012                3167.5           2712.0                40.0
...                     ...              ...                 ...
WH494                3139.0           1614.0                76.0
WH495                3416.0           1803.5               122.0
WH496                4862.0           4621.0               264.0
WH499                3740.5           3330.5               167.5
WH500                4798.0           2861.0               136.0

[137 rows x 3 columns]

In [ ]:
warehouse_inventory.sort_values('Backorder_Quantity', ascending=False)

              Current_Stock  Demand_Forecast  Backorder_Quantity
Warehouse_ID
WH449                2484.0           2155.0               300.0
WH134                 582.0            979.0               300.0
WH453                1322.0           4183.0               299.0
WH483                 583.0           3301.0               298.0
WH077                4930.0           1596.0               293.0
...                     ...              ...                 ...
WH454                2838.0           3097.0                 9.0
WH459                1295.0           2782.0                 8.0
WH407                2469.0           4680.0                 4.0
WH031                1343.0            848.0                 2.0
WH302                2867.0           2066.0                 0.0

[313 rows x 3 columns]

In [ ]:
(df['Current_Stock'] / df['Warehouse_Capacity']).describe()

count    500.000000
mean       0.110979
std        0.082087
min        0.010913
25%        0.052661
50%        0.091283
75%        0.141313
max        0.442484
dtype: float64

In [ ]:
warehouse_capacity_view = (
    df.groupby('Warehouse_ID')
    .agg({
        'Current_Stock': 'mean',
        'Demand_Forecast': 'mean',
        'Warehouse_Capacity': 'mean'
    })
)

In [ ]:
capacity_constrained_warehouses = warehouse_capacity_view[
    warehouse_capacity_view['Demand_Forecast'] >
    warehouse_capacity_view['Warehouse_Capacity']
]
capacity_constrained_warehouses

Empty DataFrame
Columns: [Current_Stock, Demand_Forecast, Warehouse_Capacity]
Index: []

## **OBJECTIVE 3**

In [13]:
df['Demand_Forecast'].describe()

count     500.000000
mean     2957.050000
std      1398.763988
min       402.000000
25%      1745.750000
50%      3094.000000
75%      4152.500000
max      5200.000000
Name: Demand_Forecast, dtype: float64

In [14]:
(df['Demand_Forecast'] - df['Current_Stock']).describe()

count     500.000000
mean      234.228000
std      2003.662878
min     -4275.000000
25%     -1188.500000
50%       209.000000
75%      1747.250000
max      4575.000000
dtype: float64

In [15]:
df.groupby('Warehouse_ID')[['Demand_Forecast','Current_Stock','Backorder_Quantity']].mean()

              Demand_Forecast  Current_Stock  Backorder_Quantity
Warehouse_ID
WH001                  3637.5         3764.0                31.5
WH002                  2175.0         4387.0               137.0
WH005                  3482.0         2669.5               101.0
WH006                  4858.0         1314.0                70.0
WH007                  2988.5         3308.0                31.0
...                       ...            ...                 ...
WH494                  1614.0         3139.0                76.0
WH495                  1803.5         3416.0               122.0
WH496                  4621.0         4862.0               264.0
WH499                  3330.5         3740.5               167.5
WH500                  2861.0         4798.0               136.0

[313 rows x 3 columns]

In [16]:
df.groupby(
    pd.cut(df['Demand_Forecast'], bins=5)
)['Backorder_Quantity'].mean()

/tmp/ipython-input-1429517053.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

Demand_Forecast
(397.202, 1361.6]    153.655556
(1361.6, 2321.2]     136.166667
(2321.2, 3280.8]     150.287129
(3280.8, 4240.4]     144.681416
(4240.4, 5200.0]     150.848214
Name: Backorder_Quantity, dtype: float64

In [17]:
df.groupby('Product_Category')[['Demand_Forecast','Backorder_Quantity']].mean()

                  Demand_Forecast  Backorder_Quantity
Product_Category
Apparel               2839.628319          157.300885
Automotive            2936.404494          140.887640
Electronics           3108.060000          147.290000
Furniture             2919.301075          147.139785
Groceries             2990.533333          142.504762

In [22]:
df.groupby('Location')[['Current_Stock','Demand_Forecast','Backorder_Quantity']].mean()

               Current_Stock  Demand_Forecast  Backorder_Quantity
Location
Atlanta          2855.163636      3184.945455          153.072727
Chicago          2701.477273      2610.363636          129.431818
Dallas           3021.313725      2980.843137          180.470588
Denver           2860.000000      2995.956522          143.804348
Houston          2432.545455      3350.681818          151.818182
Los Angeles      2843.592593      2742.277778          160.000000
Miami            2606.910714      3112.571429          138.303571
New York         2765.129630      2872.351852          127.259259
San Francisco    2526.134615      2853.057692          142.134615
Seattle          2559.454545      2849.477273          146.113636

In [24]:
location_product_table = (
    df.groupby(['Location', 'Product_Category'])
    .agg({
        'Demand_Forecast': 'mean',
        'Current_Stock': 'mean',
        'Backorder_Quantity': 'mean'
    })
    .reset_index()
    .sort_values(by='Backorder_Quantity', ascending=False)
)

location_product_table

,Location,Product_Category,Demand_Forecast,Current_Stock,Backorder_Quantity
19,Denver,Groceries,2578.142857,2702.000000,205.285714
30,Miami,Apparel,2498.090909,3013.181818,191.909091
12,Dallas,Electronics,4116.125000,2186.500000,189.875000
2,Atlanta,Electronics,3173.666667,3330.416667,188.083333
14,Dallas,Groceries,2480.312500,3187.375000,187.750000
26,Los Angeles,Automotive,2874.428571,2802.714286,187.285714
10,Dallas,Apparel,2840.777778,3990.000000,181.777778
25,Los Angeles,Apparel,2842.600000,2864.333333,181.200000
18,Denver,Furniture,2873.222222,3621.444444,178.333333
11,Dallas,Automotive,3083.500000,3173.400000,171.100000
29,Los Angeles,Groceries,2085.333333,2806.777778,169.000000
3,Atlanta,Furniture,2710.142857,2779.500000,168.285714
47,Seattle,Electronics,2507.833333,2556.333333,167.666667
33,Miami,Furniture,2886.666667,2455.833333,167.250000
13,Dallas,Furniture,2875.875000,2244.125000,166.750000
15,Denver,Apparel,2759.000000,2508.272727,165.454545
45,Seattle,Apparel,2558.272727,2477.090909,165.090909
22,Houston,Electronics,3393.363636,2582.454545,162.909091
21,Houston,Automotive,2223.714286,2064.428571,162.428571
36,New York,Automotive,2491.111111,2818.222222,162.333333
43,San Francisco,Furniture,2808.714286,2477.571429,154.857143
27,Los Angeles,Electronics,2983.454545,2723.909091,153.818182
23,Houston,Furniture,3333.111111,2166.000000,152.888889
9,Chicago,Groceries,2263.666667,2368.750000,152.416667
42,San Francisco,Electronics,2830.000000,2836.166667,152.333333
40,San Francisco,Apparel,2957.090909,2588.818182,150.454545
1,Atlanta,Automotive,3688.400000,2747.600000,149.700000
20,Houston,Apparel,3371.875000,1854.500000,145.250000
46,Seattle,Automotive,3100.222222,2118.555556,140.000000
8,Chicago,Furniture,3511.000000,2356.000000,139.875000
35,New York,Apparel,3056.437500,1985.500000,139.187500
24,Houston,Groceries,4173.777778,3316.000000,134.777778
41,San Francisco,Automotive,1970.571429,2027.714286,134.571429
32,Miami,Electronics,3093.900000,2699.300000,129.000000
39,New York,Groceries,2798.642857,3311.214286,128.857143
44,San Francisco,Groceries,3227.733333,2487.400000,125.466667
5,Chicago,Apparel,2619.400000,3098.800000,125.400000
0,Atlanta,Apparel,2918.454545,2611.363636,125.090909
7,Chicago,Electronics,1914.000000,2986.571429,118.714286
31,Miami,Automotive,3446.307692,2504.846154,117.461538
4,Atlanta,Groceries,3769.875000,2744.375000,116.625000
28,Los Angeles,Furniture,2811.416667,2978.833333,116.500000
48,Seattle,Furniture,2951.714286,3129.857143,115.857143
49,Seattle,Groceries,3715.600000,2743.200000,106.000000
16,Denver,Automotive,2900.400000,3025.900000,103.100000
37,New York,Electronics,3337.750000,3045.125000,98.250000
6,Chicago,Automotive,2858.857143,2814.000000,94.571429
38,New York,Furniture,2557.285714,3066.714286,84.857143
34,Miami,Groceries,3644.400000,2381.600000,81.000000
17,Denver,Electronics,3839.444444,2467.000000,80.222222

In [19]:
df.groupby('Stockout_Risk')['Backorder_Quantity'].mean()

Stockout_Risk
5     162.960000
6     112.440000
7     123.900000
8     126.588235
9     125.320000
10    154.800000
11    125.958333
12    160.826087
13    175.133333
14    134.375000
15    150.586207
16    166.324324
17    150.107143
18    131.739130
19    153.440000
20    145.842105
21    138.411765
22    158.857143
23    168.259259
24    126.850000
25    163.166667
Name: Backorder_Quantity, dtype: float64

## **OBJECTIVE 4**

In [39]:
df['Monthly_Sales'].describe()

count     500.000000
mean     5335.572000
std      2619.353688
min      1004.000000
25%      2978.000000
50%      5234.000000
75%      7550.750000
max      9931.000000
Name: Monthly_Sales, dtype: float64

In [40]:
df.groupby('Location')['Monthly_Sales'].mean().sort_values(ascending=False)

Location
Chicago          5943.840909
Atlanta          5907.636364
Houston          5653.090909
Denver           5558.978261
San Francisco    5366.846154
New York         5322.962963
Miami            5308.321429
Dallas           5251.450980
Los Angeles      4711.462963
Seattle          4337.795455
Name: Monthly_Sales, dtype: float64

In [41]:
df.groupby('Product_Category')['Monthly_Sales'].mean().sort_values(ascending=False)

Product_Category
Electronics    5600.570000
Furniture      5553.311828
Automotive     5443.359551
Groceries      5160.200000
Apparel        4999.920354
Name: Monthly_Sales, dtype: float64

In [44]:
location_product_sales = (
    df.groupby(['Location', 'Product_Category'])['Monthly_Sales']
    .mean()
    .reset_index()
    .sort_values(by='Monthly_Sales', ascending=False)
)

location_product_sales

         Location Product_Category  Monthly_Sales
7         Chicago      Electronics    7189.285714
43  San Francisco        Furniture    6937.714286
24        Houston        Groceries    6802.111111
2         Atlanta      Electronics    6726.416667
36       New York       Automotive    6623.777778
5         Chicago          Apparel    6544.600000
19         Denver        Groceries    6355.857143
3         Atlanta        Furniture    6312.071429
6         Chicago       Automotive    6274.285714
16         Denver       Automotive    6176.800000
18         Denver        Furniture    6125.777778
23        Houston        Furniture    6092.333333
10         Dallas          Apparel    6053.555556
32          Miami      Electronics    5867.400000
22        Houston      Electronics    5845.545455
12         Dallas      Electronics    5820.375000
34          Miami        Groceries    5731.700000
8         Chicago        Furniture    5694.125000
13         Dallas        Furniture    5685.250000
4         Atlanta        Groceries    5616.375000
41  San Francisco       Automotive    5604.142857
42  San Francisco      Electronics    5589.000000
0         Atlanta          Apparel    5554.363636
31          Miami       Automotive    5445.384615
11         Dallas       Automotive    5393.700000
21        Houston       Automotive    5392.285714
38       New York        Furniture    5388.714286
35       New York          Apparel    5310.125000
15         Denver          Apparel    5262.545455
44  San Francisco        Groceries    5256.533333
27    Los Angeles      Electronics    5249.545455
37       New York      Electronics    4992.750000
1         Atlanta       Automotive    4980.500000
30          Miami          Apparel    4902.000000
28    Los Angeles        Furniture    4899.916667
47        Seattle      Electronics    4857.333333
29    Los Angeles        Groceries    4752.333333
33          Miami        Furniture    4713.583333
9         Chicago        Groceries    4690.416667
49        Seattle        Groceries    4679.600000
39       New York        Groceries    4657.214286
25    Los Angeles          Apparel    4450.133333
46        Seattle       Automotive    4366.444444
14         Dallas        Groceries    4210.000000
40  San Francisco          Apparel    4124.272727
26    Los Angeles       Automotive    4050.285714
17         Denver      Electronics    4048.222222
45        Seattle          Apparel    4039.545455
20        Houston          Apparel    3829.875000
48        Seattle        Furniture    3634.857143

In [47]:
df['Total_Cost'] = (
    df['Operational_Cost'] +
    df['Transportation_Cost'] +
    df['Storage_Cost']
)

df['Profit'] = df['Monthly_Sales'] - df['Total_Cost']

In [48]:
df['Profit'].describe()

count       500.000000
mean     -78815.702000
std       22219.320918
min     -130570.000000
25%      -97483.000000
50%      -78697.000000
75%      -61388.750000
max      -28877.000000
Name: Profit, dtype: float64

In [53]:
df.groupby('Location')['Profit'].mean().sort_values(ascending=True)

Location
Los Angeles     -84292.000000
Miami           -81468.839286
Seattle         -80860.068182
San Francisco   -79588.038462
Denver          -78840.760870
Houston         -78413.704545
New York        -78265.370370
Atlanta         -76869.927273
Dallas          -74708.607843
Chicago         -74004.863636
Name: Profit, dtype: float64

In [54]:
df.groupby('Product_Category')['Profit'].mean().sort_values(ascending=True)

Product_Category
Apparel       -82157.592920
Automotive    -78739.707865
Electronics   -77798.950000
Furniture     -77616.301075
Groceries     -77314.266667
Name: Profit, dtype: float64

In [51]:
location_product_profit = (
    df.groupby(['Location', 'Product_Category'])['Profit']
    .mean()
    .reset_index()
    .sort_values(by='Profit', ascending=True)
)

location_product_profit

         Location Product_Category        Profit
22        Houston      Electronics -93165.272727
27    Los Angeles      Electronics -91176.454545
25    Los Angeles          Apparel -90822.333333
20        Houston          Apparel -89779.000000
41  San Francisco       Automotive -89129.428571
18         Denver        Furniture -87758.888889
48        Seattle        Furniture -87439.428571
16         Denver       Automotive -85054.400000
28    Los Angeles        Furniture -84904.000000
45        Seattle          Apparel -84353.363636
33          Miami        Furniture -83216.833333
34          Miami        Groceries -83131.500000
32          Miami      Electronics -81702.300000
39       New York        Groceries -81566.500000
30          Miami          Apparel -81080.272727
4         Atlanta        Groceries -81043.500000
35       New York          Apparel -80658.750000
44  San Francisco        Groceries -80513.600000
14         Dallas        Groceries -80296.375000
0         Atlanta          Apparel -80205.454545
15         Denver          Apparel -80099.818182
46        Seattle       Automotive -79781.333333
7         Chicago      Electronics -79180.428571
36       New York       Automotive -78788.444444
31          Miami       Automotive -78725.538462
1         Atlanta       Automotive -78426.500000
3         Atlanta        Furniture -77967.428571
26    Los Angeles       Automotive -77911.714286
40  San Francisco          Apparel -77847.090909
47        Seattle      Electronics -77788.916667
5         Chicago          Apparel -77608.600000
10         Dallas          Apparel -77463.222222
9         Chicago        Groceries -77394.250000
43  San Francisco        Furniture -76470.571429
42  San Francisco      Electronics -76279.666667
37       New York      Electronics -75843.625000
13         Dallas        Furniture -74921.000000
6         Chicago       Automotive -73990.142857
21        Houston       Automotive -73340.857143
49        Seattle        Groceries -73276.200000
19         Denver        Groceries -72622.000000
11         Dallas       Automotive -72186.000000
29    Los Angeles        Groceries -69140.222222
2         Atlanta      Electronics -68452.416667
23        Houston        Furniture -68393.000000
38       New York        Furniture -68287.714286
17         Denver      Electronics -66316.555556
24        Houston        Groceries -64247.777778
12         Dallas      Electronics -63375.000000
8         Chicago        Furniture -59900.375000

In [60]:
df['Profit_Efficiency'] = df['Monthly_Sales'] / df['Total_Cost']

df.groupby(['Location','Product_Category'])['Profit_Efficiency'].mean().sort_values(ascending=False)

Location       Product_Category
Houston        Groceries           0.099023
Dallas         Electronics         0.093792
Atlanta        Electronics         0.093493
San Francisco  Furniture           0.090406
Houston        Furniture           0.089772
Denver         Groceries           0.088545
Chicago        Furniture           0.088440
               Electronics         0.086953
               Automotive          0.086297
               Apparel             0.083403
New York       Automotive          0.081991
Atlanta        Furniture           0.081478
Miami          Electronics         0.078920
San Francisco  Electronics         0.078767
Dallas         Apparel             0.077759
Los Angeles    Groceries           0.074970
New York       Furniture           0.074846
Dallas         Furniture           0.074096
Houston        Automotive          0.071119
Denver         Automotive          0.070140
Dallas         Automotive          0.069444
San Francisco  Groceries           0.069329
Miami          Groceries           0.068219
Atlanta        Automotive          0.068191
               Apparel             0.067319
               Groceries           0.066706
Miami          Automotive          0.065975
Seattle        Electronics         0.065826
Denver         Apparel             0.065403
New York       Apparel             0.065068
Chicago        Groceries           0.063869
Denver         Furniture           0.063859
Seattle        Groceries           0.063411
New York       Electronics         0.063043
Houston        Electronics         0.060983
Los Angeles    Electronics         0.060438
Denver         Electronics         0.060229
Dallas         Groceries           0.059915
Miami          Apparel             0.058891
New York       Groceries           0.058284
Miami          Furniture           0.058281
San Francisco  Automotive          0.058019
Los Angeles    Furniture           0.057707
               Apparel             0.057208
San Francisco  Apparel             0.056435
Seattle        Automotive          0.055807
Los Angeles    Automotive          0.050646
Seattle        Apparel             0.050212
               Furniture           0.043875
Houston        Apparel             0.039126
Name: Profit_Efficiency, dtype: float64

In [59]:
df.groupby(['Location','Product_Category'])['Backorder_Quantity'].mean().sort_values(ascending=False)

Location       Product_Category
Denver         Groceries           205.285714
Miami          Apparel             191.909091
Dallas         Electronics         189.875000
Atlanta        Electronics         188.083333
Dallas         Groceries           187.750000
Los Angeles    Automotive          187.285714
Dallas         Apparel             181.777778
Los Angeles    Apparel             181.200000
Denver         Furniture           178.333333
Dallas         Automotive          171.100000
Los Angeles    Groceries           169.000000
Atlanta        Furniture           168.285714
Seattle        Electronics         167.666667
Miami          Furniture           167.250000
Dallas         Furniture           166.750000
Denver         Apparel             165.454545
Seattle        Apparel             165.090909
Houston        Electronics         162.909091
               Automotive          162.428571
New York       Automotive          162.333333
San Francisco  Furniture           154.857143
Los Angeles    Electronics         153.818182
Houston        Furniture           152.888889
Chicago        Groceries           152.416667
San Francisco  Electronics         152.333333
               Apparel             150.454545
Atlanta        Automotive          149.700000
Houston        Apparel             145.250000
Seattle        Automotive          140.000000
Chicago        Furniture           139.875000
New York       Apparel             139.187500
Houston        Groceries           134.777778
San Francisco  Automotive          134.571429
Miami          Electronics         129.000000
New York       Groceries           128.857143
San Francisco  Groceries           125.466667
Chicago        Apparel             125.400000
Atlanta        Apparel             125.090909
Chicago        Electronics         118.714286
Miami          Automotive          117.461538
Atlanta        Groceries           116.625000
Los Angeles    Furniture           116.500000
Seattle        Furniture           115.857143
               Groceries           106.000000
Denver         Automotive          103.100000
New York       Electronics          98.250000
Chicago        Automotive           94.571429
New York       Furniture            84.857143
Miami          Groceries            81.000000
Denver         Electronics          80.222222
Name: Backorder_Quantity, dtype: float64

In [62]:
df.groupby(['Product_Category','Location'])[['Return_Rate','Damaged_Goods']].mean().sort_values(by='Return_Rate', ascending=False)

                                Return_Rate  Damaged_Goods
Product_Category Location
Furniture        Denver            7.497483      29.666667
Automotive       Los Angeles       6.927560      22.000000
Apparel          Miami             6.865176      25.909091
Electronics      Atlanta           6.748723      21.916667
Apparel          Seattle           6.620376      30.181818
Electronics      Los Angeles       6.620065      27.000000
                 Denver            6.619286      31.222222
Automotive       New York          6.189504      27.555556
                 Denver            5.943087      23.500000
Electronics      New York          5.931749      31.750000
Automotive       Atlanta           5.913385      20.600000
Electronics      Dallas            5.868733      24.750000
Groceries        Seattle           5.821063      18.000000
                 Denver            5.802771      18.857143
                 Chicago           5.756617      27.416667
Electronics      Miami             5.705138      30.300000
Apparel          New York          5.627546      29.312500
Furniture        Chicago           5.594607      18.375000
                 Dallas            5.575914      16.000000
Groceries        San Francisco     5.504442      27.466667
Furniture        San Francisco     5.504277      22.428571
Automotive       Houston           5.456613      20.428571
Furniture        Los Angeles       5.374146      19.750000
Apparel          Chicago           5.338078      30.200000
Electronics      Seattle           5.233249      27.000000
Groceries        Atlanta           5.037316      14.875000
Automotive       Seattle           5.004581      22.333333
Electronics      Houston           4.988248      24.000000
Apparel          San Francisco     4.933145      24.454545
Furniture        Atlanta           4.922207      22.428571
Groceries        Dallas            4.846236      23.625000
Automotive       Miami             4.783948      23.923077
Groceries        Miami             4.754099      23.400000
Electronics      San Francisco     4.723425      27.833333
Furniture        Miami             4.721336      19.250000
Apparel          Los Angeles       4.684233      17.266667
Groceries        New York          4.657921      27.714286
Apparel          Dallas            4.607425      26.555556
                 Atlanta           4.534962      26.909091
Electronics      Chicago           4.432778      31.285714
Furniture        Houston           4.295919      18.111111
Apparel          Denver            4.235828      24.090909
Automotive       Chicago           4.234671      31.285714
Apparel          Houston           4.141941      29.625000
Automotive       Dallas            4.058724      24.200000
Furniture        New York          3.965111      26.857143
Groceries        Los Angeles       3.917777      25.111111
Automotive       San Francisco     3.888918      16.285714
Furniture        Seattle           3.864310      30.000000
Groceries        Houston           2.814924      25.444444

In [63]:
df.groupby(['Location','Product_Category'])[['Customer_Rating','Monthly_Sales']].mean()

                                Customer_Rating  Monthly_Sales
Location      Product_Category
Atlanta       Apparel                  3.221877    5554.363636
              Automotive               2.621250    4980.500000
              Electronics              3.410559    6726.416667
              Furniture                2.811477    6312.071429
              Groceries                3.107471    5616.375000
Chicago       Apparel                  3.006350    6544.600000
              Automotive               3.703627    6274.285714
              Electronics              2.658990    7189.285714
              Furniture                3.776563    5694.125000
              Groceries                2.975646    4690.416667
Dallas        Apparel                  3.398435    6053.555556
              Automotive               3.352482    5393.700000
              Electronics              3.162734    5820.375000
              Furniture                2.995079    5685.250000
              Groceries                3.409624    4210.000000
Denver        Apparel                  2.751321    5262.545455
              Automotive               3.086481    6176.800000
              Electronics              3.220915    4048.222222
              Furniture                3.174010    6125.777778
              Groceries                2.572042    6355.857143
Houston       Apparel                  2.573593    3829.875000
              Automotive               3.658470    5392.285714
              Electronics              3.461986    5845.545455
              Furniture                2.990082    6092.333333
              Groceries                2.860767    6802.111111
Los Angeles   Apparel                  2.484233    4450.133333
              Automotive               3.779898    4050.285714
              Electronics              2.997731    5249.545455
              Furniture                2.843552    4899.916667
              Groceries                2.327076    4752.333333
Miami         Apparel                  3.712383    4902.000000
              Automotive               3.298146    5445.384615
              Electronics              3.127299    5867.400000
              Furniture                3.290106    4713.583333
              Groceries                3.376509    5731.700000
New York      Apparel                  2.956792    5310.125000
              Automotive               2.856745    6623.777778
              Electronics              3.025743    4992.750000
              Furniture                3.050130    5388.714286
              Groceries                2.904113    4657.214286
San Francisco Apparel                  3.103142    4124.272727
              Automotive               2.589384    5604.142857
              Electronics              3.226934    5589.000000
              Furniture                3.497284    6937.714286
              Groceries                2.882791    5256.533333
Seattle       Apparel                  3.213992    4039.545455
              Automotive               3.071339    4366.444444
              Electronics              3.468687    4857.333333
              Furniture                2.615491    3634.857143
              Groceries                3.138576    4679.600000

In [33]:
df[['Transportation_Cost','Storage_Cost','Operational_Cost']].describe()

       Transportation_Cost  Storage_Cost  Operational_Cost
count           500.000000     500.00000        500.000000
mean           8001.086000   10263.83400      65886.354000
std            4269.354045    5584.14567      20283.576821
min             515.000000    1083.00000      30165.000000
25%            4294.500000    5335.75000      48731.750000
50%            7973.000000   10023.00000      65733.500000
75%           11857.000000   15162.00000      82900.250000
max           14988.000000   19979.00000      99965.000000

In [35]:
df.groupby('Shipping_Time_Days')[['Transportation_Cost','Storage_Cost','Operational_Cost']].mean()

                    Transportation_Cost  Storage_Cost  Operational_Cost
Shipping_Time_Days
1                           8379.925373  11142.940299      64861.074627
2                           8335.338235  10058.308824      64791.500000
3                           8370.878049   9443.073171      70205.304878
4                           8302.142857  10847.142857      66184.168831
5                           7454.810127   9676.177215      67577.734177
6                           7782.179104  10565.074627      63668.582090
7                           7271.200000  10325.583333      62236.850000

In [36]:
df.groupby('Location')[['Transportation_Cost','Storage_Cost','Operational_Cost']].mean().sort_values(ascending=False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [28]:
df.groupby(pd.cut(df['Employee_Count'], bins=5))['Order_Processing_Time'].mean()

/tmp/ipython-input-2014779720.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

Employee_Count
(4.905, 24.0]    2.662007
(24.0, 43.0]     2.886434
(43.0, 62.0]     2.625670
(62.0, 81.0]     2.959986
(81.0, 100.0]    2.650571
Name: Order_Processing_Time, dtype: float64

In [29]:
(df['Current_Stock'] / df['Warehouse_Capacity']).describe()

count    500.000000
mean       0.110979
std        0.082087
min        0.010913
25%        0.052661
50%        0.091283
75%        0.141313
max        0.442484
dtype: float64

In [31]:
df.groupby(pd.cut(df['Transportation_Cost'], bins=5))['Backorder_Quantity'].mean()

/tmp/ipython-input-3831161683.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df['Transportation_Cost'], bins=5)

Transportation_Cost
(500.527, 3409.6]     148.698925
(3409.6, 6304.2]      137.951456
(6304.2, 9198.8]      146.260000
(9198.8, 12093.4]     150.011628
(12093.4, 14988.0]    153.601695
Name: Backorder_Quantity, dtype: float64

In [37]:
df.groupby(pd.cut(df['Storage_Cost'], bins=5))['Backorder_Quantity'].mean()

/tmp/ipython-input-2062364780.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df['Storage_Cost'], bins=5))['Backorder_Quantity'].mean()

Storage_Cost
(1064.104, 4862.2]    145.471698
(4862.2, 8641.4]      145.870690
(8641.4, 12420.6]     127.651163
(12420.6, 16199.8]    156.130435
(16199.8, 19979.0]    160.070000
Name: Backorder_Quantity, dtype: float64

In [38]:
df.groupby(pd.cut(df['Operational_Cost'], bins=5))['Backorder_Quantity'].mean()

/tmp/ipython-input-3971137371.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df['Operational_Cost'], bins=5))['Backorder_Quantity'].mean()

Operational_Cost
(30095.2, 44125.0]    151.956044
(44125.0, 58085.0]    138.500000
(58085.0, 72045.0]    154.763441
(72045.0, 86005.0]    142.752381
(86005.0, 99965.0]    150.242991
Name: Backorder_Quantity, dtype: float64